version: '3'
services:
  middleware:
    build: .
    command: ./middleware
    ports:
      - "8090:8090"
    depends_on:
      - node-1
      - node-2
      - node-3

  node-1:
    build: .
    command: ./node
    environment:
      - NODE_ID=1
    ports:
      - "8081:8080"

  node-2:
    build: .
    command: ./node
    environment:
      - NODE_ID=2
    ports:
      - "8082:8080"

  node-3:
    build: .
    command: ./node
    environment:
      - NODE_ID=3
    ports:
      - "8083:8080"