version: '3'
services:
  middleware:
    build: .
    command: ./middleware
    ports:
      - "8090:8090"
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4

  node-1:
    build: .
    command: ./node
    environment:
      - NODE_ID=1
      - DB_HOST=db-1
    ports:
      - "8081:8080"
    depends_on:
      - db-1

  node-2:
    build: .
    command: ./node
    environment:
      - NODE_ID=2
    ports:
      - "8082:8080"
    depends_on:
      - db-2


  node-3:
    build: .
    command: ./node
    environment:
      - NODE_ID=3
    ports:
      - "8083:8080"
    depends_on:
      - db-3


  node-4:
    build: .
    command: ./node
    environment:
      - NODE_ID=4
    ports:
      - "8084:8080"
    depends_on:
      - db-4


  db-1:
    image: postgres:13
    environment:
      POSTGRES_DB: nodedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata1:/var/lib/postgresql/data

  db-2:
    image: postgres:13
    environment:
      POSTGRES_DB: nodedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata2:/var/lib/postgresql/data


  db-3:
    image: postgres:13
    environment:
      POSTGRES_DB: nodedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata3:/var/lib/postgresql/data


  db-4:
    image: postgres:13
    environment:
      POSTGRES_DB: nodedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata4:/var/lib/postgresql/data


volumes:
  pgdata1:
  pgdata2:
  pgdata3:
  pgdata4: