version: '3'
services:
  node-1:
    build: .
    environment:
      - NODE_ID=1
    ports:
      - "8081:8080"
  node-2:
    build: .
    environment:
      - NODE_ID=2
    ports:
      - "8082:8080"
  node-3:
    build: .
    environment:
      - NODE_ID=3
    ports:
      - "8083:8080"