# docker-compose.yml
version: '3.8'
services:
  mongodb1:
    image: mongo:latest
    container_name: iam_server_1
    ports:
      - "27017:27017"
    networks:
      - iam_network

  mongodb2:
    image: mongo:latest
    container_name: iam_server_2
    ports:
      - "27018:27017"
    networks:
      - iam_network

  mongodb3:
    image: mongo:latest
    container_name: iam_server_3
    ports:
      - "27019:27017"
    networks:
      - iam_network

networks:
  iam_network:
    driver: bridge